### ISSUE TITLE
7.0.6 Crash

### ISSUE THREAD

**Issue by mmind99** [thecoder75/liveme-tools#119]
7.0.6 starts up and gets to the main screen.  Its sits there for about 5 seconds, then crashes getting this...
![untitled](https://user-images.githubusercontent.com/33794328/33212212-046f74f4-d0f0-11e7-9768-4eacae1c2f18.png)
![untitled2](https://user-images.githubusercontent.com/33794328/33212297-5e9b2f7c-d0f0-11e7-873f-d9a6fee48577.png)

Win 7 Ultimate

**Comment by thecoder75** [comment]
Should be fixed now in the 7.0.7 release.

**Comment by mmind99** [comment]
Still see the same thing in 7.0.7.  One thing to note.  Until 7.0.6, I never saw the splash screen on my Win 7 system.  I saw it on the Win 10 system all along.  Not sure if it has anything to do with it, but it crashes around the time I see the splash screen.

![untitled](https://user-images.githubusercontent.com/33794328/33222141-f5ecf70c-d122-11e7-9fd5-4a707c734319.png)
